sudo: required
services:
  - docker

before_install:
  - docker build -t uday1005/dkr-react-aws-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true uday1005/dkr-react-aws-frontend npm run test
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dkr-react-aws-test"
  env: "DkrReactAwsTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-785136939258"
  bucket_path: "dkr-react-aws-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
