sudo: required
services:
  - docker

before_install:
  - docker build -t uday1005/dkr-react-aws-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true uday1005/dkr-react-aws-frontend npm run test
